FROM schedfuzz-base

RUN apt install -y autopoint po4a
# ImageMagick specifics -- should split into separate file
WORKDIR /opt
RUN git clone https://github.com/xz-mirror/xz.git

WORKDIR /opt/xz
RUN mkdir build
RUN ./autogen.sh
RUN ./configure --disable-shared --prefix=/opt/xz/build
RUN make -j $(nproc); make install
ENV UNINST=/opt/xz/build/bin/xz

RUN mkdir afl_testcases; cd afl_testcases; wget https://lcamtuf.coredump.cx/afl/demo/afl_testcases.tgz; tar -zxvf afl_testcases.tgz
ENV INPUTS=/opt/xz/afl_testcases/png/edges-only/images
ENV SUT_NAME=xz

# Steps to run
# ------------

# e9afl instrument

WORKDIR /opt/sched-fuzz
RUN ./instrument.sh $UNINST

# only takes 1st arg, so i.e. a random input
ENV ARGS="-z @@ -T 4 --stdout > o.xz"
RUN python3 ./dynamic-pp.py $INPUTS/*
RUN cp out.csv /opt/out

# compress
CMD ./fuzz.sh -i $INPUTS -o /opt/out -d -t 8000 -- ./$SUT_NAME.afl -z @@ -T 4 -kf

# remove sudo for privileged docker container
# sudo sysctl -w kernel.core_pattern="core-%e"
# cd /sys/devices/system/cpu; echo performance | sudo tee cpu*/cpufreq/scaling_governor

# docker build . -t fuzzer
# mkdir out
# docker run -v $(pwd)/out:/opt/run fuzzer

